workflows:
  android-build:
    name: Asset View Android Build
    # Ang 'linux' ay ang standard na libre/mura na instance
    instance_type: linux 
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - target_platform_android
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk